### ISSUE TITLE
XPop Service Dies...

### ISSUE THREAD

**Issue by lathanbritz** [Xahau/Validation-Ledger-Tx-Store-to-xPOP#5]
the server can run for some time and then when I tries to get the updated UNL from https://vl.xrplf.org/
```

Obtained ledger (binary) store/0/83/647/550 83647550 TX# 54
Obtained ledger (JSON object) store/0/83/647/550 83647550 Hash EF1AFB7DC1835EFFE9E2AD45A4802EB64DE9EB60408ABCB598C0F12C167930A9
Obtained ledger (binary) store/0/83/647/551 83647551 TX# 46
Obtained ledger (JSON object) store/0/83/647/551 83647551 Hash CBBA9EBB488B9290F39FF3DCA1E2B9F770E019EED84DF17A0B5B93AF290D5591
file:///usr/src/app/node_modules/node-fetch/src/index.js:108
			reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
			       ^

FetchError: request to https://vl.xrplf.org/ failed, reason: 
    at ClientRequest.<anonymous> (file:///usr/src/app/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: undefined
}

Node.js v20.9.0
Running backend version 3.1.0
Started Event Socket Service at TCP port 3000
<<<<< CONNECTING >>>>>
* * * CONNECTING wss://xrplcluster.com
* * * CONNECTING wss://s2.ripple.com
Fetched UNL https://vl.xrplf.org found validators 35
Obtained ledger (binary) store/0/83/647/553 83647553 TX# 51
Obtained ledger (JSON object) store/0/83/647/553 83647553 Hash 1950369454D44776736548C92942A4FB9EA55B265B91B7CDB57C059DE3AD9F01
Obtained ledger (binary) store/0/83/647/554 83647554 TX# 39
Obtained ledger (JSON object) store/0/83/647/554 83647554 Hash 3EEAF5D99D5B9878C9236F33AD04F91374903E66DB60014107CA6D9463A1FC1C


```

it falls over and restarts

**Comment by WietseWind** [comment]
@lathanbritz I checked my logs on three different nodes and this never happened.

I suspect it's something local, DNS, ... fetching the URL (?)

I'll update the code to prevent it falling over if this happens and keep on using the old record, but I think this indicates some connectivity issues on either end of the connection, this isn't something we can actually fix in the code :( (Except for the falling over)

**Comment by lathanbritz** [comment]
Rippled reports same issues in its log mainnet, alloy as I understand knows about the intermittent issue on the UNL fetch.

**Comment by WietseWind** [comment]
Even more interesting, so then there's an issue with the hosting provider (Netlify) I assume.

**Comment by WietseWind** [comment]
@lathanbritz Nice catch. I updated the code (publishing in a sec) to deal gracefully with not being able to fetch UNL;
- If first call (and nothing known): error out and restart
- If follow up call & previous results known: continue and try again every now and then

<img width="1080" alt="image" src="https://github.com/Xahau/Validation-Ledger-Tx-Store-to-xPOP/assets/4756161/14816850-af53-40f8-bb84-bb05b9481e66">
